name: Compile Arduino Code
on: 
  push:
    paths:
    - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile Source Code on Arduino CLI
      run: bash ci/build-arduino.sh