name: Compile Arduino Code
on:
  push:
    paths:
      - ".github/workflows/compile_action.yaml"
      - "src/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "me-no-dev/ESPAsyncWebServer"
          path: $HOME/Arduino/libraries/ESPAsyncWebServer
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "me-no-dev/ESPAsyncTCP"
          path: $HOME/Arduino/libraries/ESPAsyncTCP
      - name: Compile Source Code on Arduino CLI
        run: bash ci/build-arduino.sh
