name: Compress Webpage and transform to C Header
on:
  push:
    paths:
    - '.github/workflows/html_compression_action.yaml'
    - 'tools/**'
    - 'src/Webpage/html_uncompressed/**'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
        architecture: 'x64' 
    - name: Pip install requirements
      run: pip install -r tools/requirements.txt
    - name: Compress HTML files
      run: python tools/html_compresser.py
    - name: Convert compressed HTML files to C++ headers
      run: python tools/html_to_c_converter.py
    - name: Commit and push changes
      run: |
          git config --global user.name 'Nico Weidenfeller'
          git config --global user.email 'iot@nicoweidenfeller.com'
          git add -A
          git commit -am "Automated report"
          git push
